### ISSUE TITLE
From Bracken output to BIOM?

### ISSUE THREAD

**Issue by MaryoHg** [dnasko/refseq_rollback#1]
Dear Dan (@dnasko).

I was reading your 2018 publication at Genome Biology and I found it very helpful.
I'm not being able to use the scripts you mentioned over my Bracken-output data.

May I ask you for a little guidance?

My question is that I can't find de _-h_ option for your script and be able to use them correctly,
Do you have some _readme.md_ extended version, or something?

I appreciate any comment.

Respectfully,

MaryoHg.

**Comment by dnasko** [comment]
Hi @MaryoHg, thank you for reaching out and I'm sorry that you're running into an issue.

Which script specifically are you having an issue with?

**Comment by MaryoHg** [comment]
Thanks for reply @dnasko.

Reading through your work I was intended to follow this instructions (and use this paper as a reference):

>The “dump_taxonomy_species.pl” script in
the refseq_rollback repository was used to convert the
NCBI taxonomy ID on each line to its species name.
Using this file, an operational taxonomic unit (OTU)
table was constructed at the species- and genus-levels
using the “create_otu_table.pl” in the refseq_rollback re-
pository. The OTU table was imported to QIIME1 [...].
Source: [https://doi.org/10.1186/s13059-018-1554-6](https://genomebiology.biomedcentral.com/articles/10.1186/s13059-018-1554-6)

There is a difference between the approach that you and I followed (I think): I used a "custom" database for Kraken v1.0 analysis for each metagenome I have (following the instructions manual for Kraken ([See here](https://ccb.jhu.edu/software/kraken2/index.shtml?t=manual#custom-databases)). So I'm not sure how to construct my OTU table using the _create_otu_table.pl_ from your repository.

I apologize if I not being clear about my issue.
What I want to do is to convert my 'all-samples-joined'-Bracken's (Specie level) output to a BIOM table with your script and be able to do diversity metrics through QIIME, as you did.

Thank you Dan for any comment further.
Sorry If I'm being a waste of your time.



MaryoHg.

**Comment by dnasko** [comment]
Hi @MaryoHg,

Never a waste of time :)

I misunderstood your question at first, but having gone through this a bit today I think I see the problem here. So the scripts in this repository can only generate an OTU table of a given version of RefSeq using two files from NCBI's taxonomy database and the RefSeq "release" file.

It can't create an OTU table of results from Kraken or Bracken. Though, I think that's a pretty neat idea and if you pass along your output file I might be able to whip up a parser to do that for you.

I've updated the repository to include some example input files that these scripts use and I've updated the scripts to include more documentation on inputs/outputs.

Please let me know if this clarifies things for you. If so we can close this issue and chat further about making an OTU file from Kraken and Bracken outputs.

**Comment by MaryoHg** [comment]
Hi again, @dnasko 

It think I misunderstood the workflow.
> So the scripts in this repository can only generate an OTU table of a given version of RefSeq using two files from NCBI's taxonomy database and the RefSeq "release" file.

Thank you, It is clear to me now. Even, I'll talk to my fellows to give it a try and have some fun. :flushed:


Now, just to be clear, with this:
> I think that's a pretty neat idea and if you pass along your output file I might be Abel to whip up a parser to do that for you.

..you mean that I can send you my outputs and you'll help me to be able to go through my issue? 
If yes, please, e-mail me at hg.maryo[at]gmail.com. I'll sent sent the files as response.


¡THANK YOU @dnasko!  

Respectfully,
MaryoHg.
